# Application Name
spring.application.name=springAI-service

# Application running Port
server.port=8084

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=phi3:mini

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=vnIKZ-+KDGaOf4S8fK8V

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_database
spring.datasource.username=SPRINGBOOT
spring.datasource.password=${MY_SQL_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.main.allow-bean-definition-overriding=true
#spring.data.mongodb.uri= mongodb+srv://milkonwheelDBUser:Abhinav3031%40%40@cluster0.ag6uvsw.mongodb.net/first_index?appName=Cluster0
#spring.data.mongodb.uri= mongodb+srv://milkonwheelDBUser:Abhinav3031@@@cluster0.gb3im.mongodb.net/milkonwheelDB?retryWrites=true&w=majority
#spring.data.mongodb.uri=mongodb://milkonwheelDBUser:Abhinav3031%40%40@ac-tmliagi-shard-00-00.ag6uvsw.mongodb.net:27017,ac-tmliagi-shard-00-01.ag6uvsw.mongodb.net:27017,ac-tmliagi-shard-00-02.ag6uvsw.mongodb.net:27017/?ssl=true&replicaSet=atlas-ap000t-shard-0&authSource=admin&appName=Cluster0